In [1]:
import pandas as pd 
import numpy as np


In [2]:
df=pd.read_csv('mall customers.csv')

In [3]:
df.head()

CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
df=df.drop('CustomerID',axis=1)

In [5]:
df

Gender  Age  Annual Income (k$)  Spending Score (1-100)
0      Male   19                  15                      39
1      Male   21                  15                      81
2    Female   20                  16                       6
3    Female   23                  16                      77
4    Female   31                  17                      40
..      ...  ...                 ...                     ...
195  Female   35                 120                      79
196  Female   45                 126                      28
197    Male   32                 126                      74
198    Male   32                 137                      18
199    Male   30                 137                      83

[200 rows x 4 columns]

# Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
df.Gender=label.fit_transform(df['Gender'])


In [7]:
df.Gender

0      1
1      1
2      0
3      0
4      0
      ..
195    0
196    0
197    1
198    1
199    1
Name: Gender, Length: 200, dtype: int32

In [8]:
df    #male 1 , female 0

Gender  Age  Annual Income (k$)  Spending Score (1-100)
0         1   19                  15                      39
1         1   21                  15                      81
2         0   20                  16                       6
3         0   23                  16                      77
4         0   31                  17                      40
..      ...  ...                 ...                     ...
195       0   35                 120                      79
196       0   45                 126                      28
197       1   32                 126                      74
198       1   32                 137                      18
199       1   30                 137                      83

[200 rows x 4 columns]

In [9]:
df.columns

Index(['Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)'], dtype='object')

In [10]:
x=df[['Gender', 'Age', 'Spending Score (1-100)']]

In [11]:
x

Gender  Age  Spending Score (1-100)
0         1   19                      39
1         1   21                      81
2         0   20                       6
3         0   23                      77
4         0   31                      40
..      ...  ...                     ...
195       0   35                      79
196       0   45                      28
197       1   32                      74
198       1   32                      18
199       1   30                      83

[200 rows x 3 columns]

In [12]:
y=df['Annual Income (k$)']

In [13]:
y

0       15
1       15
2       16
3       16
4       17
      ... 
195    120
196    126
197    126
198    137
199    137
Name: Annual Income (k$), Length: 200, dtype: int64

In [14]:
df.isnull().sum()

Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

# LR  with multiple variable

In [15]:
x

Gender  Age  Spending Score (1-100)
0         1   19                      39
1         1   21                      81
2         0   20                       6
3         0   23                      77
4         0   31                      40
..      ...  ...                     ...
195       0   35                      79
196       0   45                      28
197       1   32                      74
198       1   32                      18
199       1   30                      83

[200 rows x 3 columns]

In [16]:
y

0       15
1       15
2       16
3       16
4       17
      ... 
195    120
196    126
197    126
198    137
199    137
Name: Annual Income (k$), Length: 200, dtype: int64

# Validation training testing data

In [17]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=2)

In [18]:
xtrain

Gender  Age  Spending Score (1-100)
28        0   40                      31
133       0   31                      71
94        0   32                      42
42        1   48                      36
169       1   32                      63
..      ...  ...                     ...
43        0   31                      61
22        0   46                       5
72        0   60                      49
15        1   22                      79
168       0   36                      27

[140 rows x 3 columns]

In [19]:
ytrain

28     29
133    72
94     60
42     39
169    87
       ..
43     39
22     25
72     50
15     20
168    87
Name: Annual Income (k$), Length: 140, dtype: int64

In [20]:
xtest

Gender  Age  Spending Score (1-100)
112       0   38                      42
29        0   23                      87
182       1   46                      15
199       1   30                      83
193       0   38                      91
85        1   48                      46
10        1   67                      14
54        0   50                      45
115       0   19                      50
35        0   21                      81
12        0   58                      15
92        1   48                      49
13        0   24                      77
126       1   43                      35
174       0   52                      13
2         0   20                       6
44        0   49                      28
3         0   23                      77
113       1   19                      46
14        1   37                      13
23        1   31                      73
25        1   29                      82
6         0   35                       6
134       1   20                       5
165       0   36                      75
173       1   36                      92
45        0   24                      65
65        1   18                      59
48        0   29                      42
122       0   40                      58
178       1   59                      14
64        1   63                      51
9         0   30                      72
57        1   69                      46
78        0   23                      52
71        0   47                      42
128       1   59                      11
176       1   58                      15
131       1   39                      75
53        1   59                      60
137       1   32                      73
163       0   31                      93
111       0   19                      54
123       1   39                      91
109       1   66                      48
141       1   32                      93
41        1   24                      92
130       1   47                       9
140       0   57                       5
5         0   22                      76
159       0   30                      73
100       0   23                      41
11        0   35                      99
187       1   28                      68
24        0   54                      14
89        0   50                      46
66        0   43                      50
8         1   64                       3
172       1   36                      10
175       0   30                      86

In [21]:
ytest

112     64
29      29
182     98
199    137
193    113
85      54
10      19
54      43
115     65
35      33
12      20
92      60
13      20
126     71
174     88
2       16
44      39
3       16
113     64
14      20
23      25
25      28
6       18
134     73
165     85
173     87
45      39
65      48
48      40
122     69
178     93
64      48
9       19
57      44
78      54
71      49
128     71
176     88
131     71
53      43
137     73
163     81
111     63
123     69
109     63
141     75
41      38
130     71
140     75
5       17
159     78
100     62
11      19
187    101
24      28
89      58
66      48
8       19
172     87
175     88
Name: Annual Income (k$), dtype: int64

In [22]:
len(xtest)

60

In [23]:
len(xtrain)

140

# calling LR model with multiple variable

In [24]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [25]:
reg.fit(xtrain,ytrain)

LinearRegression()

In [26]:
reg.coef_

array([-1.4869205 , -0.09726096, -0.04340959])

In [27]:
reg.intercept_     #m1=-1.4869205 ,m2= -0.09726096,m3= -0.04340959 and c=69.00080143093338

69.00080143093338

In [28]:
y1=(-1.4869205*0)+(-0.09726096*38)+(-0.04340959*42)+69.00080143093338

In [29]:
y1

63.48168217093338

In [30]:
reg.predict([[0,38,42]])

array([63.48168221])

In [35]:
y_pred =reg.predict(xtest)
y_pred

array([63.48168221, 62.98716527, 62.38873283, 60.99305637, 61.35461248,
       60.84851373, 60.38966219, 62.18432189, 64.98236382, 63.44214471,
       62.70852178, 60.71828497, 63.32400017, 61.812324  , 63.37890673,
       66.79512465, 63.01954582, 63.42126113, 63.66908166, 63.35090067,
       61.32989127, 61.13372692, 65.3362102 , 65.35161374, 62.24368779,
       60.01880432, 63.84491521, 63.202018  , 64.35703088, 62.5926069 ,
       61.1677499 , 59.17255135, 62.95748232, 58.80603351, 64.50650079,
       62.60633354, 61.29797866, 61.22160128, 60.4649844 , 59.17090893,
       61.23263031, 61.94862005, 64.80872547, 59.77043101, 59.01099722,
       60.36443858, 61.18593587, 62.55192939, 63.2398786 , 63.56193168,
       62.91407274, 64.98400624, 61.29911868, 61.83872209, 63.14097522,
       62.14091231, 62.6481007 , 61.15895053, 63.5783904 , 62.34974811])

In [32]:
ytest.head()

112     64
29      29
182     98
199    137
193    113
Name: Annual Income (k$), dtype: int64

# Accuracy

In [33]:
reg.score(xtest,ytest)

-0.07703184113165884

# R^2 Value

In [36]:
from sklearn.metrics import r2_score
Score=r2_score(ytest,y_pred)
Score

-0.07703184113165884

# KNN regressor with multiple variable

In [37]:
from sklearn.neighbors import KNeighborsRegressor
regressor=KNeighborsRegressor()
regressor.fit(xtrain,ytrain)


KNeighborsRegressor()

In [38]:
predicted_y=regressor.predict(xtest)
predicted_y

array([ 68. ,  56.4,  68.6,  80.6,  84.6,  58.2,  55. ,  57.8,  57.8,
        36.2,  72.4,  52.4,  39.6,  54.4,  68.4,  84.6,  72.6,  25.2,
        52.4,  94.8,  79.2,  80. ,  85.8,  84.6,  84. ,  81.2,  44. ,
        45.2,  46.6,  47.2,  63.4,  55.4,  82.4,  55. ,  55.8,  55.8,
        58.8,  72.4,  93.8,  54. ,  76.6,  86.6,  53.2,  84.6,  56.8,
        86.6,  55.8,  65.8,  38.8,  25.2,  79.2,  50.4,  71.2,  64.2,
        73. ,  55.8,  54.4,  38.8, 102.6,  84.6])

In [39]:
regressor.predict([[0,38,42]])

array([68.])

# Accuracy

In [40]:
regressor.score(xtest,ytest)

-0.06562390886397274